[package]
  cjc-version = "1.0.0"
  name = "dgengine"
  description = "DGEngine game engine"
  version = "2.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std"
  override-compile-option = "--dy-std"
  link-option = ""
  package-configuration = {}

[dependencies]
  cenum = { path = "dependencies/cenum" }
  cjsfml = { path = "dependencies/cjsfml" }
  ctemplate = { path = "dependencies/ctemplate" }
  customiterators = { path = "dependencies/customiterators" }
  endian = { path = "dependencies/endian" }
  physfs4cj = { path = "dependencies/physfs4cj" }
  stdjson2 = { path = "dependencies/stdjson2" }
  stdlog = { path = "dependencies/stdlog" }
